### ISSUE TITLE
Le fichier .dot ne se créer pas (aucune erreur de compilation)

### ISSUE THREAD

**Issue by lutzilutz** [kyouko-taiga/PetriKit#1]
Avec le code suivant dans mon main.swift, le fichier pn.dot n'est pas créée, quel que soit le réseau de Petri pn que j'essaie de créer. De même, print() ne fonctionne pas ... Pourtant, si je rajoute une erreur volontaire, des messages d'erreurs apparaissent, ce qui veut dire que je compile bien le bon dossier. Le fichier pn.dot résiste à être créée, alors que le package est bien importé et que le terminal ne m'indique aucune erreur de compilation.

import Foundation
import PetriKit
import TaskManagerLib

let taskManager = createTaskManager()
let taskPool    = taskManager.places.first { $0.name == "taskPool" }!
let create   = taskManager.transitions.first { $0.name == "create" }!

print("Hello ?")

let pn = PTNet(places: [taskPool], transitions: [create])
try pn.saveAsDot(to: URL(fileURLWithPath: "pn.dot"), withMarking: [taskPool: 1])

(noob en swift, et noob en github, mon erreur est peut-être flagrante pour des yeux plus affutés)

**Comment by kyouko-taiga** [comment]
Je n'arrive pas à reproduire ton erreur. Peux-tu m'indiquer les commandes que tu exécutes dans le terminal?

**Comment by lutzilutz** [comment]
Mh, je fais seulement le build : "swift build"

**Comment by kyouko-taiga** [comment]
Le problème a été réglé après un passage dans mon bureau. Le problème était qu'il faut non seulement build le programme mais aussi l'exécuter.
